spring.application.name=Build-week-Back-End-3
spring.datasource.url=jdbc:postgresql://localhost:5432/BuildWeekJava
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=2462
jwt.secret=2fd9fef5-c023-4088-af7b-e1673a439712